* 小说
** 开头
咖啡厅
小姐姐
水洗耶加
称豆，暖杯，闷蒸
娴熟的二段式冲泡
1：15
柠檬与花香

“你听说过数字电路吗？”

“哈？”

** 楔子
如往常一般，踏入了这家熟悉的咖啡店，咖啡店的装潢很随意，就是一个老居民楼的墙上开了个洞。
我倒是蛮喜欢这儿的，没有x巴克，x平洋的嘈杂，也可以坐在吧台前和小姐姐聊聊咖啡和巧克力，算起来，我应该归不到身边那些一个月只能和食堂大妈讨价还价的麻辣老里吧。

“你的水洗耶加“

虽然一直不怎么习惯跟女性聊天，但最近和这个店员小姐姐聊天好像渐渐没那么拘谨了，可能是兴趣比较接近吧，虽然咖啡一直很火，但是手冲咖啡毕竟还是比较小众的，能遇到爱好者大家都是互相珍惜的。
而且每次讲到咖啡，店员小姐姐就打开了话匣子，最近看书尝试了几种新手法啊，进了啥新豆啊。。。虽然我对咖啡也只是入门，不过一个妹子在你面前那么有干劲的描述一项事情，相信对于大部分人来说都是很有吸引力的吧。

“嗯，酸度适中，甜感比较突出，还有这花香，果然我还是喜欢耶加雪啡呀，还是说手法有什么变化了呢“

既然她这么热情的向我介绍热爱的事物，我也试着跟她展现一下我所热爱的世界吧。

“这份是我的自信之作呢，倒是你，今天怎么没像往常一样点一杯浓缩呢？“

“这不是很久没喝耶加了吗，恰巧看到你今天进的红樱桃，对了，你的手法确实厉害，不过有没有想过你帮我做浓缩的那台机器是怎么运作的吗？”

“或者说，你听说过数字电路吗？”

“哈？”

** 二进制引入
“呃。。。其实我高中的时候数学一直不好。。。”

”没关系，虽然数字电路本质确实是离散数学，不过它的发展历程和实现其实是充满了故事的，而且这是一个由一个元器件就可以构建出来的世界哦“

”听不太懂。。。不过平时也是一直聊咖啡，听点不同的也是挺有意思的呢。“

”好，那我们先来学习一下数字电路基础的前置知识哦，一定要记住，这很重要，也很难。“

”好，我会努力理解的。”

“你觉得事物最常见的基本状态有多少种呢，比如电灯。”

“这个好说吧，不就两种吗，开和关”

“好了，学完了。”

“哈？”

** 二进制
“别那么吃惊嘛，欧几里德当初也是只用四条定理就建立了欧式几何的世界嘛，就是我们学的那个几何。”

“说是这么说，你这个就开和关能干啥呀。”

“你可别小看了这开和关，等下你就知道了，开关的发明可是这世界上最伟大的发明。”

“行了行了，你就说说看吧。”

“虽然不是所有，但是我们生活中的计算离不开数字对吧，你一般使用几根手指计算呢，但愿你不是古巴比伦人。”

“十根，嗯？“

“很好，至少说明你不是残疾人，别生气，不是骂你啦，确实有些人天生比较难受，可能少几根手指，或者多几根手指，六指琴魔听过叭，有没有想过，这些人刚开始学用手指头计算的时候是怎么用手指的呢？”

“好麻烦啊，为啥不用计算器呢“

“我觉得这也是人类的浪漫之一吧，所有人类的造物基本上都是由几个简单的器件或者简单的原理组合叠加，然后他就能完成许多复杂的运作了，不觉得很浪漫吗？话说你还没回答我问题呢。”

“行叭。。。六指琴魔还好说，少用一根手指就好了，那些少于十根手指的人我是真不知道。”

“他们改造计算方式就好啦！”

“哈？那他们算出来的东西能和我们一样吗，不一样不就没有意义了吗。。。”

“不用那么惊讶嘛，他们算出来的东西确实不一样，不过你听过外国人对话吗，小时候你应该还听不懂叭。”

“抱歉呀，我其实是小时候生活在国外，十二岁之后才回国的。”

“。。。行叭，那你听过陶什罗语吗“

“什么？什么东西？”

“我也不知道，我刚百度的，不过，说陶什罗语的人肯定听得懂陶什罗语吧。“

“那是自然，像我说中文你听得懂一样。”

“那就好，你想想看啊，那同样的，用八根手指计算规则的人，是不是也看得懂八根手指计算出来的数字呢？”

“对呀，可是，我们大部分人还是看不懂啊”

“你会说英语吗，你会说中文吗？”

“你说我现在在跟你讲什么。。。就算不会也有翻译软件啊”

“那就对了呀，翻译嘛，就像人和human，虽然写起来读起来都不同，可是他们不是一个意思吗，这八根手指的人数的东西和十根手指的人数的东西不一样多吗？“

“那倒是，这么说，可以通过翻译的方法让我们大部分的人读懂这八根手指的人写的东西了吗？”

“没错！说到底也是数同一个东西嘛，翻译方法的话我后面再讲给你听吧，这可是收费的哦，一杯意式起价哦。我们现在来说说另一个残疾人叭，这个残疾人比较惨，两只手都不见了，不过人家意志坚强，通过自身努力，还是学会了用手算术。”

“手都没了怎么算？”

“用手臂啊，这不还有两只手臂吗，这样也可以，只不过算起来比较麻烦，他必须逢二进一，其实这背后的进位思想很重要的，我下次讲给你听。不过他其实也比较幸运，不用记住0到9十个数字，只要记住0和1两个就好了，熟练的话其实只用记更少的计算规则，不像我们还要背乘法口诀表什么的。其实这和我们早期计算机的原理差不多哦。“

“我看计算器都是用十进制的啊。”

“都说了，那是翻译给你看的啦，其实他基本使用的是二进制，不过也有使用十进制的著名计算机，ENIAC听过吧，他用的就是十进制，不过他的下一代有一个大改变，就是使用了二进制，二进制其实是充分利用了机器特性的，还记得刚刚跟你说的开关吗？“

“哦！他的开和关是二进制？“

“特性相同啦，不过因为特性相符，可以大大降低机器的复杂度和提高机器的运算速度，还是十分重要的。对了，不知你有没有听过一句话”二进制是计算机的基础“，其实这句话不完全正确的，虽然当前机器确实使用的是二进制，不过其实不用二进制也是可以的，像那个都市传说”苏联黑科技三进制计算机领先世界许多年“其实也只是都市传说而已，三进制计算机也不是啥黑科技啦，你愿意的话，我现在就可以给你做个一进制计算机。”

“怎么做啊？”

“给我几根牙签，我数一个东西放一个牙签，比如我数三个咖啡豆，就摆三根牙签，记做111，这不比三进制还黑科技？不过由于只有一个数字，没有占位符，所以我也不知他算不算进位。这可是几千年前发明的欸，结绳计事，虽然实际上不太好用就是了，所以当今机器基本上使用的是二进制。”

“然后呢？”

“太晚啦，下次在讲叭，记得请我喝咖啡哦。”

** 进位
舒服，今天的是星期天，也是个好日子，完成项目后突然间出现了不用熬夜的日子，昨晚十二点睡觉后直接睡到十点自然醒，像是回到了大学时候。
那时候我还是个莫名被电路迷住的家伙呢。
午饭后无意识的就到了咖啡厅，星期天的人也不多，奇怪，平时也不见很多客人啊，她到底是靠什么撑下这个店面的呢？

“你来了啊，最近有新烘的水洗洪都拉斯瑰夏。不来搞一杯？见你有一阵子没来了。”

“可行，最近有个项目压着，哪有时间偷跑出来啊。”

“那我就一比十五给你冲咯，你上次讲到哪里来着？”

“上次讲二进制嘛，怎么，对电路感兴趣了？”

“咩兴趣”

“行叭，反正今天看你也闲，就打扰你做生意了。”

“反正也不会倒闭，你在这讲说不定还能拉下客，这地段程序员也多。”

“会数数吗？”

“？？？”

“哎呀，就是从一数到无穷大嘛，别看他简单，其实里面有个特别重要的机制，你猜得到吗。”

“你的瑰夏。”

“。。。其实是进位，就是逢十进一那个进位啦，别小看这个机制，这是数学史上的一个大发明。早期数学对于人类其实纯粹是个工具而已，实用是第一要素。不过后来有个数字是被发明出来的，你猜是哪个？”

“零到九不都是被发明出来的吗？”

“额。。。其实一到九其实算是被发现出来的吧，而零不同哦，一和其他数字一样，分别代表几个数字，而零不同，零代表什么都没有，对于平时来说，零基本上派不上用场，你会经常说你有零个东西吗？”

“那零也就是个数字啊，有啥特别的。。。”

“别小看这个零哦，我先给你说说进位制吧，你知道为啥人们要使用进位制吗”

“不知道，数学家们闲得慌？”

“快给我向数学家们道歉，如果不是他们，你今天可能得记上万种符号，没错，进位的一个作用其实是解决符号需要不断发明的问题的，你想想看，如果不进位，你数到十写啥，我姑且用a来代替，十一呢？一直数下去呢？”

“好啦好啦，我认输，你这样逼问女孩子，没有女朋友吧。”

“你。。。你不要凭空污人清白，女朋友这种事，工科生能叫没有吗，有什么比科学与数学更像女朋友的！”

“呵，我看你是什么都不懂哦。”

“好。。。好啦，回来说进位啦，零在进位制里充当一个占位符的作用，啥是占位符，说白了就是占着位子不干活，不，占着位子的符号，你看看，我们是逢十进一对吧，你看看，9和10，有什么区别？”

“一个数字和两个数字的区别嘛”

“对了，10前面那个1代表前面进了1位，已经有一个十了，后面那个0表示从什么都没有，即从新开始计数，你想想看，要是没有0，这个空缺不就没办法表示了吗，数学家还是有点头脑的吧。”

“你的瑰夏凉了。”

“！！！我的瑰夏(´ﾟДﾟ`)”

“好啦好啦，看你讲的口干舌燥的，我送你一杯吧。”

“说送就送的嘛。。。这可是瑰夏啊。”

“不要就算咯”

“要要要，那我下次就给你讲如何开始组建数字电路了，这些前置知识你也了解了吧。很好”

“球球李摇了我叭。”
** TODO 逻辑运算

